package com.country;

import com.vividsolutions.jts.geom.Point;
import com.vividsolutions.jts.geom.Coordinate;
import com.vividsolutions.jts.geom.GeometryFactory;

public class CountryDecoder {

  public static String decode(double latitude, double longitude) {
    Point p = new GeometryFactory().createPoint(new Coordinate(longitude, latitude));
    if (AntiguaandBarbuda.test(p)) return "Antigua and Barbuda";
    if (Algeria.test(p)) return "Algeria";
    if (Azerbaijan.test(p)) return "Azerbaijan";
    if (Albania.test(p)) return "Albania";
    if (Armenia.test(p)) return "Armenia";
    if (Angola.test(p)) return "Angola";
    if (AmericanSamoa.test(p)) return "American Samoa";
    if (Argentina.test(p)) return "Argentina";
    if (Australia.test(p)) return "Australia";
    if (Bahrain.test(p)) return "Bahrain";
    if (Barbados.test(p)) return "Barbados";
    if (Bermuda.test(p)) return "Bermuda";
    if (Bahamas.test(p)) return "Bahamas";
    if (Bangladesh.test(p)) return "Bangladesh";
    if (Belize.test(p)) return "Belize";
    if (BosniaandHerzegovina.test(p)) return "Bosnia and Herzegovina";
    if (Bolivia.test(p)) return "Bolivia";
    if (Burma.test(p)) return "Burma";
    if (Benin.test(p)) return "Benin";
    if (SolomonIslands.test(p)) return "Solomon Islands";
    if (Brazil.test(p)) return "Brazil";
    if (Bulgaria.test(p)) return "Bulgaria";
    if (BruneiDarussalam.test(p)) return "Brunei Darussalam";
    if (Canada.test(p)) return "Canada";
    if (Cambodia.test(p)) return "Cambodia";
    if (SriLanka.test(p)) return "Sri Lanka";
    if (Congo.test(p)) return "Congo";
    if (DemocraticRepublicoftheCongo.test(p)) return "Democratic Republic of the Congo";
    if (Burundi.test(p)) return "Burundi";
    if (China.test(p)) return "China";
    if (Afghanistan.test(p)) return "Afghanistan";
    if (Bhutan.test(p)) return "Bhutan";
    if (Chile.test(p)) return "Chile";
    if (CaymanIslands.test(p)) return "Cayman Islands";
    if (Cameroon.test(p)) return "Cameroon";
    if (Chad.test(p)) return "Chad";
    if (Comoros.test(p)) return "Comoros";
    if (Colombia.test(p)) return "Colombia";
    if (CostaRica.test(p)) return "Costa Rica";
    if (CentralAfricanRepublic.test(p)) return "Central African Republic";
    if (Cuba.test(p)) return "Cuba";
    if (CapeVerde.test(p)) return "Cape Verde";
    if (CookIslands.test(p)) return "Cook Islands";
    if (Cyprus.test(p)) return "Cyprus";
    if (Denmark.test(p)) return "Denmark";
    if (Djibouti.test(p)) return "Djibouti";
    if (Dominica.test(p)) return "Dominica";
    if (DominicanRepublic.test(p)) return "Dominican Republic";
    if (Ecuador.test(p)) return "Ecuador";
    if (Egypt.test(p)) return "Egypt";
    if (Ireland.test(p)) return "Ireland";
    if (EquatorialGuinea.test(p)) return "Equatorial Guinea";
    if (Estonia.test(p)) return "Estonia";
    if (Eritrea.test(p)) return "Eritrea";
    if (ElSalvador.test(p)) return "El Salvador";
    if (Ethiopia.test(p)) return "Ethiopia";
    if (Austria.test(p)) return "Austria";
    if (CzechRepublic.test(p)) return "Czech Republic";
    if (FrenchGuiana.test(p)) return "French Guiana";
    if (Finland.test(p)) return "Finland";
    if (Fiji.test(p)) return "Fiji";
    if (FalklandIslandsMalvinas.test(p)) return "Falkland Islands (Malvinas)";
    if (MicronesiaFederatedStatesof.test(p)) return "Micronesia, Federated States of";
    if (FrenchPolynesia.test(p)) return "French Polynesia";
    if (France.test(p)) return "France";
    if (Gambia.test(p)) return "Gambia";
    if (Gabon.test(p)) return "Gabon";
    if (Georgia.test(p)) return "Georgia";
    if (Ghana.test(p)) return "Ghana";
    if (Grenada.test(p)) return "Grenada";
    if (Greenland.test(p)) return "Greenland";
    if (Germany.test(p)) return "Germany";
    if (Guam.test(p)) return "Guam";
    if (Greece.test(p)) return "Greece";
    if (Guatemala.test(p)) return "Guatemala";
    if (Guinea.test(p)) return "Guinea";
    if (Guyana.test(p)) return "Guyana";
    if (Haiti.test(p)) return "Haiti";
    if (Honduras.test(p)) return "Honduras";
    if (Croatia.test(p)) return "Croatia";
    if (Hungary.test(p)) return "Hungary";
    if (Iceland.test(p)) return "Iceland";
    if (India.test(p)) return "India";
    if (IranIslamicRepublicof.test(p)) return "Iran (Islamic Republic of)";
    if (Israel.test(p)) return "Israel";
    if (Italy.test(p)) return "Italy";
    if (CotedIvoire.test(p)) return "Cote d'Ivoire";
    if (Iraq.test(p)) return "Iraq";
    if (Japan.test(p)) return "Japan";
    if (Jamaica.test(p)) return "Jamaica";
    if (Jordan.test(p)) return "Jordan";
    if (Kenya.test(p)) return "Kenya";
    if (Kyrgyzstan.test(p)) return "Kyrgyzstan";
    if (KoreaDemocraticPeoplesRepublicof.test(p)) return "Korea, Democratic People's Republic of";
    if (Kiribati.test(p)) return "Kiribati";
    if (KoreaRepublicof.test(p)) return "Korea, Republic of";
    if (Kuwait.test(p)) return "Kuwait";
    if (Kazakhstan.test(p)) return "Kazakhstan";
    if (LaoPeoplesDemocraticRepublic.test(p)) return "Lao People's Democratic Republic";
    if (Lebanon.test(p)) return "Lebanon";
    if (Latvia.test(p)) return "Latvia";
    if (Belarus.test(p)) return "Belarus";
    if (Lithuania.test(p)) return "Lithuania";
    if (Liberia.test(p)) return "Liberia";
    if (Slovakia.test(p)) return "Slovakia";
    if (Liechtenstein.test(p)) return "Liechtenstein";
    if (LibyanArabJamahiriya.test(p)) return "Libyan Arab Jamahiriya";
    if (Madagascar.test(p)) return "Madagascar";
    if (Martinique.test(p)) return "Martinique";
    if (Mongolia.test(p)) return "Mongolia";
    if (Montserrat.test(p)) return "Montserrat";
    if (TheformerYugoslavRepublicofMacedonia.test(p)) return "The former Yugoslav Republic of Macedonia";
    if (Mali.test(p)) return "Mali";
    if (Morocco.test(p)) return "Morocco";
    if (Mauritius.test(p)) return "Mauritius";
    if (Mauritania.test(p)) return "Mauritania";
    if (Malta.test(p)) return "Malta";
    if (Oman.test(p)) return "Oman";
    if (Maldives.test(p)) return "Maldives";
    if (Mexico.test(p)) return "Mexico";
    if (Malaysia.test(p)) return "Malaysia";
    if (Mozambique.test(p)) return "Mozambique";
    if (Malawi.test(p)) return "Malawi";
    if (NewCaledonia.test(p)) return "New Caledonia";
    if (Niue.test(p)) return "Niue";
    if (Niger.test(p)) return "Niger";
    if (Aruba.test(p)) return "Aruba";
    if (Anguilla.test(p)) return "Anguilla";
    if (Belgium.test(p)) return "Belgium";
    if (HongKong.test(p)) return "Hong Kong";
    if (NorthernMarianaIslands.test(p)) return "Northern Mariana Islands";
    if (FaroeIslands.test(p)) return "Faroe Islands";
    if (Andorra.test(p)) return "Andorra";
    if (Gibraltar.test(p)) return "Gibraltar";
    if (IsleofMan.test(p)) return "Isle of Man";
    if (Luxembourg.test(p)) return "Luxembourg";
    if (Macau.test(p)) return "Macau";
    if (Monaco.test(p)) return "Monaco";
    if (Palestine.test(p)) return "Palestine";
    if (Montenegro.test(p)) return "Montenegro";
    if (Mayotte.test(p)) return "Mayotte";
    if (landIslands.test(p)) return "?land Islands";
    if (NorfolkIsland.test(p)) return "Norfolk Island";
    if (CocosKeelingIslands.test(p)) return "Cocos (Keeling) Islands";
    if (Antarctica.test(p)) return "Antarctica";
    if (BouvetIsland.test(p)) return "Bouvet Island";
    if (FrenchSouthernandAntarcticLands.test(p)) return "French Southern and Antarctic Lands";
    if (HeardIslandandMcDonaldIslands.test(p)) return "Heard Island and McDonald Islands";
    if (BritishIndianOceanTerritory.test(p)) return "British Indian Ocean Territory";
    if (ChristmasIsland.test(p)) return "Christmas Island";
    if (UnitedStatesMinorOutlyingIslands.test(p)) return "United States Minor Outlying Islands";
    if (Vanuatu.test(p)) return "Vanuatu";
    if (Nigeria.test(p)) return "Nigeria";
    if (Netherlands.test(p)) return "Netherlands";
    if (Norway.test(p)) return "Norway";
    if (Nepal.test(p)) return "Nepal";
    if (Nauru.test(p)) return "Nauru";
    if (Suriname.test(p)) return "Suriname";
    if (Nicaragua.test(p)) return "Nicaragua";
    if (NewZealand.test(p)) return "New Zealand";
    if (Paraguay.test(p)) return "Paraguay";
    if (Peru.test(p)) return "Peru";
    if (Pakistan.test(p)) return "Pakistan";
    if (Poland.test(p)) return "Poland";
    if (Panama.test(p)) return "Panama";
    if (Portugal.test(p)) return "Portugal";
    if (PapuaNewGuinea.test(p)) return "Papua New Guinea";
    if (GuineaBissau.test(p)) return "Guinea-Bissau";
    if (Qatar.test(p)) return "Qatar";
    if (Reunion.test(p)) return "Reunion";
    if (Romania.test(p)) return "Romania";
    if (RepublicofMoldova.test(p)) return "Republic of Moldova";
    if (Philippines.test(p)) return "Philippines";
    if (PuertoRico.test(p)) return "Puerto Rico";
    if (Russia.test(p)) return "Russia";
    if (Rwanda.test(p)) return "Rwanda";
    if (SaudiArabia.test(p)) return "Saudi Arabia";
    if (SaintKittsandNevis.test(p)) return "Saint Kitts and Nevis";
    if (Seychelles.test(p)) return "Seychelles";
    if (SouthAfrica.test(p)) return "South Africa";
    if (Lesotho.test(p)) return "Lesotho";
    if (Botswana.test(p)) return "Botswana";
    if (Senegal.test(p)) return "Senegal";
    if (Slovenia.test(p)) return "Slovenia";
    if (SierraLeone.test(p)) return "Sierra Leone";
    if (Singapore.test(p)) return "Singapore";
    if (Somalia.test(p)) return "Somalia";
    if (Spain.test(p)) return "Spain";
    if (SaintLucia.test(p)) return "Saint Lucia";
    if (Sudan.test(p)) return "Sudan";
    if (Sweden.test(p)) return "Sweden";
    if (SyrianArabRepublic.test(p)) return "Syrian Arab Republic";
    if (Switzerland.test(p)) return "Switzerland";
    if (TrinidadandTobago.test(p)) return "Trinidad and Tobago";
    if (Thailand.test(p)) return "Thailand";
    if (Tajikistan.test(p)) return "Tajikistan";
    if (Tokelau.test(p)) return "Tokelau";
    if (Tonga.test(p)) return "Tonga";
    if (Togo.test(p)) return "Togo";
    if (SaoTomeandPrincipe.test(p)) return "Sao Tome and Principe";
    if (Tunisia.test(p)) return "Tunisia";
    if (Turkey.test(p)) return "Turkey";
    if (Tuvalu.test(p)) return "Tuvalu";
    if (Turkmenistan.test(p)) return "Turkmenistan";
    if (UnitedRepublicofTanzania.test(p)) return "United Republic of Tanzania";
    if (Uganda.test(p)) return "Uganda";
    if (UnitedKingdom.test(p)) return "United Kingdom";
    if (Ukraine.test(p)) return "Ukraine";
    if (UnitedStates.test(p)) return "United States";
    if (BurkinaFaso.test(p)) return "Burkina Faso";
    if (Uruguay.test(p)) return "Uruguay";
    if (Uzbekistan.test(p)) return "Uzbekistan";
    if (SaintVincentandtheGrenadines.test(p)) return "Saint Vincent and the Grenadines";
    if (Venezuela.test(p)) return "Venezuela";
    if (BritishVirginIslands.test(p)) return "British Virgin Islands";
    if (VietNam.test(p)) return "Viet Nam";
    if (UnitedStatesVirginIslands.test(p)) return "United States Virgin Islands";
    if (Namibia.test(p)) return "Namibia";
    if (WallisandFutunaIslands.test(p)) return "Wallis and Futuna Islands";
    if (Samoa.test(p)) return "Samoa";
    if (Swaziland.test(p)) return "Swaziland";
    if (Yemen.test(p)) return "Yemen";
    if (Zambia.test(p)) return "Zambia";
    if (Zimbabwe.test(p)) return "Zimbabwe";
    if (Indonesia.test(p)) return "Indonesia";
    if (Guadeloupe.test(p)) return "Guadeloupe";
    if (NetherlandsAntilles.test(p)) return "Netherlands Antilles";
    if (UntiedArabEmirates.test(p)) return "Untied Arab Emirates";
    if (TimorLeste.test(p)) return "Timor-Leste";
    if (PitcairnIslands.test(p)) return "Pitcairn Islands";
    if (Palau.test(p)) return "Palau";
    if (MarshallIslands.test(p)) return "Marshall Islands";
    if (SaintPierreandMiquelon.test(p)) return "Saint Pierre and Miquelon";
    if (SaintHelena.test(p)) return "Saint Helena";
    if (SanMarino.test(p)) return "San Marino";
    if (TurksandCaicosIslands.test(p)) return "Turks and Caicos Islands";
    if (WesternSahara.test(p)) return "Western Sahara";
    if (Serbia.test(p)) return "Serbia";
    if (HolySeeVaticanCity.test(p)) return "Holy See (Vatican City)";
    if (Svalbard.test(p)) return "Svalbard";
    if (SaintMartin.test(p)) return "Saint Martin";
    if (SaintBarthelemy.test(p)) return "Saint Barthelemy";
    if (Guernsey.test(p)) return "Guernsey";
    if (Jersey.test(p)) return "Jersey";
    if (SouthGeorgiaSouthSandwichIslands.test(p)) return "South Georgia South Sandwich Islands";
    if (Taiwan.test(p)) return "Taiwan";
    return null;
  }
}
